#if defined _weapon_base_throwable_const_included
  #endinput
#endif
#define _weapon_base_throwable_const_included

stock const Weapon_BaseThrowable[] = "base_throwable";

stock const Weapon_BaseThrowable_Member_flStartThrow[] = "flStartThrow";
stock const Weapon_BaseThrowable_Member_flReleaseThrow[] = "flReleaseThrow";
stock const Weapon_BaseThrowable_Member_flThrowForce[] = "flThrowForce";
stock const Weapon_BaseThrowable_Member_flThrowPitch[] = "flThrowPitch";
stock const Weapon_BaseThrowable_Member_flProjectileSpawnDistance[] = "flProjectileSpawnDistance";
stock const Weapon_BaseThrowable_Member_bRedeploy[] = "bRedeploy";
stock const Weapon_BaseThrowable_Member_flThrowDuration[] = "flThrowDuration";
stock const Weapon_BaseThrowable_Member_bThrowOnHolster[] = "bThrowOnHolster";

stock const Weapon_BaseThrowable_Method_DestroyItem[] = "DestroyItem";
stock const Weapon_BaseThrowable_Method_ReleaseThrow[] = "ReleaseThrow";
stock const Weapon_BaseThrowable_Method_Throw[] = "Throw";
stock const Weapon_BaseThrowable_Method_SpawnProjectile[] = "SpawnProjectile";
